[project]
name = "llm-arena"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.1",
    "pydantic>=2.12.5",
    "rich>=14.2.0",
]
